Docker Build & Status Badge

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -147,9 +147,9 @@ jobs:
   build-and-deploy-image:
     docker:
       - image: cimg/python:3.9.7
-        auth:
-            username: $DOCKER_USERNAME
-            password: $DOCKER_ACCESS_CODE
+        # auth:
+        #     username: $DOCKER_USERNAME
+        #     password: $DOCKER_ACCESS_CODE
     working_directory: ~/project/dagster
     environment:
       VERSION: v.1.<<pipeline.number>>
@@ -157,7 +157,7 @@ jobs:
       - checkout
       
       - aws-cli/install # Works only for python images, need install python 
-            
+      - docker/install-docker-tools
       - setup_remote_docker
 
       - run:
@@ -175,22 +175,17 @@ jobs:
             docker load -i /caches/dagster-app.tar | true
 
       - run: 
-          name: Build Dagster Image & Contaier
+          name: Build and Test Dagster Images
           command: |
             # Your stack command code here
             echo "Building image..."
 
             echo "VERSION=${VERSION}"
-
-            cd dagster
-            docker-compose -f docker-compose-prod.yml up -d
-
-      - run: 
-          name: Test Containers
-          command: |
-            URL=localhost:3000
+           
+            docker-compose -f docker-compose-prod.yml up
 
             # Check if can connect
+            URL=localhost:3000
             curl $URL
 
             if curl $URL
@@ -200,22 +195,40 @@ jobs:
                 echo "FAILURE(-): Failed to connect to Dagster"
                 exit 1
             fi
-
-            # Check if it found relevant word.
-            if curl $URL | grep "Dagit"
-            then
-                echo "SUCCESS(++): found $2 in document: $URL\n"
-                exit 0
-            else
-                echo "FAILURE(--): Failed to find $2 in document: $URL"
-                exit 1
-            fi
             docker-compose down
+
+      # - run: 
+      #     name: Test Containers
+      #     command: |
+      #       URL=localhost:3000
+
+      #       # Check if can connect
+      #       curl $URL
+
+      #       if curl $URL
+      #       then
+      #           echo "SUCCESS(+): Connected to Dagster UI\n"
+      #       else
+      #           echo "FAILURE(-): Failed to connect to Dagster"
+      #           exit 1
+      #       fi
+
+      #       # Check if it found relevant word.
+      #       if curl $URL | grep "Dagit"
+      #       then
+      #           echo "SUCCESS(++): found $2 in document: $URL\n"
+      #           exit 0
+      #       else
+      #           echo "FAILURE(--): Failed to find $2 in document: $URL"
+      #           exit 1
+      #       fi
+      #       docker-compose down
 
       - run:
           name: Deploy to Docker Repository
           command: |
             echo "Deploying to Docker"
+            docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_CODE
             docker-compose -f docker-compose-prod.yml push
 
   # Jobs for Continuous Deployment          
